# Generated by Django 2.2 on 2020-03-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeId', models.CharField(max_length=500)),
                ('designation', models.CharField(blank=True, max_length=500)),
                ('date_of_joining', models.DateField(blank=True)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'EmployeeDetail',
                'verbose_name_plural': 'EmployeeDetails',
                'unique_together': {('employeeId', 'designation', 'date_of_joining', 'name', 'address', 'email')},
            },
        ),
    ]
