# Generated by Django 2.2 on 2020-03-03 15:37

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterUniqueTogether(
            name='employeedetail',
            unique_together={('employeeId', 'designation', 'date_of_joining', 'name', 'address', 'phone_number', 'email')},
        ),
    ]
