# Generated by Django 2.2 on 2020-03-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200303_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='employeeId',
            field=models.BigIntegerField(),
        ),
    ]
